#!/usr/bin/env bash

N_REPOS_UPDATED=0
N_REPOS_SKIPPED=0

INITIAL_PATH="$(pwd)"

INPUT_DIR="$*"

if [[ -z "$INPUT_DIR" ]]; then
  REPO_DIR="$(pwd)"
else
  REPO_DIR="$(pwd)/$INPUT_DIR"
fi

if [[ ! -d "$REPO_DIR" ]]; then
  echo "$REPO_DIR is not a directory."
  exit 1
fi

cd "$REPO_DIR" || exit 1

GIT_REPO_COUNT="$(find "$REPO_DIR" -maxdepth 1 -type d -exec test -e '{}/.git' ';' -print | wc -l)"

echo "Found $GIT_REPO_COUNT git repositories in $REPO_DIR to update..."
echo ""

for DIR in ./*; do
  if [[ ! -d "$DIR" ]]; then
    continue
  fi

  REPO="$(basename "$DIR")"

	if [[ ! -d "$DIR/.git" ]]; then
		continue
	fi

  cd "$DIR" || exit 1

	ACTIVE_REMOTE="$(git rev-parse --abbrev-ref --symbolic-full-name @\{u\} | cut -d'/' -f1)"
	ACTIVE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

	if [[ -n "$(git status --porcelain)" ]]; then
    N_REPOS_SKIPPED="$((N_REPOS_SKIPPED + 1)))"

		echo "  - $REPO has uncommitted changes, skipping..."

    cd ..
		continue
	fi

  HASH_BEFORE="$(git rev-parse HEAD)"

  git pull "$ACTIVE_REMOTE" "$ACTIVE_BRANCH" > /dev/null 2>&1

  HASH_AFTER="$(git rev-parse HEAD)"
  N_COMMITS="$(git rev-list --count "$HASH_BEFORE".."$HASH_AFTER")"

  if [[ "$HASH_BEFORE" != "$HASH_AFTER" ]]; then
    echo "  - $REPO: pulled $N_COMMITS new commits (branch $ACTIVE_BRANCH from $ACTIVE_REMOTE)"

    N_REPOS_UPDATED="$((N_REPOS_UPDATED + 1))"
  else
    echo "  - $REPO: up to date"
  fi

  cd ..
done

cd "$INITIAL_PATH" || exit 1

echo ""

if [[ -z "$N_REPOS_UPDATED" ]]; then
  echo "No repositories were updated."
else
  echo "Updated $N_REPOS_UPDATED, skipped $N_REPOS_SKIPPED git repos."
fi
